window.MakeEyecatchConfig = {
  sizeRules: {
    square: {
      label: "正方形",
      ratio: "1:1",
      prompt: "square 1:1 canvas, centered composition, iconic single subject, balanced negative space, optimized for a square image area",
      compositionJa: "中央配置を基調にした単焦点構図",
    },
    wide: {
      label: "16:9",
      ratio: "16:9",
      prompt: "landscape 16:9 canvas, wide horizontal composition, one dominant subject, generous negative space, optimized for a true 16:9 image area",
      compositionJa: "主役を1つに絞った横長構図",
    },
    portrait: {
      label: "縦長",
      ratio: "4:5",
      prompt: "portrait 4:5 canvas for Instagram, tall vertical composition, one dominant subject, balanced negative space above and below, optimized for a true 4:5 image area",
      compositionJa: "Instagram向けの主役を立てる縦長構図",
    },
  },
  baseStyleRules: {
    ukiyoe: {
      label: "浮世絵",
      look: "with subtle ukiyo-e woodblock print cues, ukiyo-e atmosphere, Edo-period aesthetics, flat perspective, strong ink outlines, delicate linework, poetic Japanese storytelling",
      composition: "subject positioned slightly right of center, wide empty space on the left side, clear clean margin on all edges, leave visible breathing room around the entire artwork, keep all elements fully inside the canvas, no visible outer border, no frame lines near the edges, no rectangular print frame, no border, no frame, no cropping, no cut edges, balanced composition with safe padding",
      texture: "woodblock print texture, washi paper texture, subtle washi roughness, slight print misalignment, traditional ink feel",
      color: "muted traditional Japanese colors, calm Japanese palette, restrained contrast, poetic and timeless mood",
      mood: "calm intensity, symbolic expression, handcrafted presence",
      negative: "no photorealism, no glossy 3D rendering, no modern objects, no complex background, no multiple subjects",
    },
    simple70s: {
      label: "1970年代",
      look: "1970s retro editorial illustration, mid-century modern style, bold flat shapes, clean but slightly rough outlines, minimal detail, iconic composition",
      composition: "iconic composition, clean layout, one dominant subject with minimal distraction",
      texture: "subtle paper grain texture, vintage print effect, slight misalignment",
      color: "limited warm color palette, muted orange and brown tones",
      mood: "calm and informative mood",
      negative: "no photorealism, no glossy 3D rendering, no anime style, no excessive detail, no multiple subjects",
    },
    original: {
      label: "オリジナル",
      look: "clean editorial illustration, flexible visual language, iconic single-subject composition",
      composition: "balanced composition, one dominant subject, enough breathing room around the main motif",
      texture: "subtle paper texture, clean handcrafted imperfection",
      color: "controlled palette, clear contrast, flexible mood-driven color balance",
      mood: "clear, versatile, usable, quietly expressive",
      negative: "no photorealism, no glossy 3D rendering, no clutter, no multiple subjects",
    },
    hokkaidoCamper: {
      label: "北海道キャンピングカー",
      look: "clean travel editorial illustration with calm outdoor atmosphere, iconic single-subject composition, friendly road-trip mood",
      composition: "one dominant camper-van related subject, spacious composition, enough room for landscape atmosphere without clutter",
      texture: "subtle paper texture, clean printed feel, light handcrafted imperfection",
      color: "natural Hokkaido-inspired palette, cool sky tones, muted greens, warm beige highlights, restrained contrast",
      mood: "open-air freedom, practical warmth, quiet travel excitement, clear usability",
      negative: "no photorealism, no glossy 3D rendering, no city clutter, no multiple subjects",
    },
    retro80s: {
      label: "1980年代",
      look: "1980s editorial illustration, geometric styling, bold silhouettes, graphic composition, slightly playful visual rhythm",
      composition: "clear focal subject, dynamic but readable layout, poster-like balance",
      texture: "light paper grain, subtle print noise, analog magazine feel",
      color: "high-contrast retro palette, teal, coral, cream, deep navy accents",
      mood: "bright, confident, energetic, informative",
      negative: "no photorealism, no glossy 3D rendering, no cyberpunk excess, no multiple subjects",
    },
    retro90s: {
      label: "1990年代",
      look: "1990s editorial illustration, approachable graphic style, soft analog shapes, clean magazine composition",
      composition: "one dominant subject, relaxed layout, simple editorial spacing",
      texture: "subtle print texture, light grain, slightly dry ink feel",
      color: "muted 1990s palette, dusty blue, burgundy, beige, moss green",
      mood: "friendly, practical, calm, informative",
      negative: "no photorealism, no glossy 3D rendering, no excessive detail, no multiple subjects",
    },
    retro2000s: {
      label: "2000年代",
      look: "2000s editorial illustration, clean vector-like forms, crisp contours, simple commercial graphic clarity",
      composition: "clear central subject, balanced whitespace, polished layout",
      texture: "light print texture, smooth digital-era finish with subtle paper feel",
      color: "fresh 2000s palette, sky blue, lime, orange, silver-gray accents",
      mood: "clean, optimistic, practical, easy to understand",
      negative: "no photorealism, no glossy 3D rendering, no clutter, no multiple subjects",
    },
    retro2010s: {
      label: "2010年代",
      look: "2010s editorial illustration, flat design influence, minimal shapes, clean contemporary composition",
      composition: "simple focal layout, organized spacing, strong visual clarity",
      texture: "very subtle paper texture, clean print finish",
      color: "flat modern palette, muted blue, coral, mustard, off-white",
      mood: "clear, modern, informative, approachable",
      negative: "no photorealism, no glossy 3D rendering, no heavy skeuomorphism, no multiple subjects",
    },
    retro2020s: {
      label: "2020年代",
      look: "2020s editorial illustration, refined digital editorial style, soft geometry, clean high-clarity composition",
      composition: "one dominant subject, generous spacing, strong readability",
      texture: "subtle grain, refined print texture, clean modern finish",
      color: "contemporary restrained palette, soft neutrals with one accent color",
      mood: "calm, polished, intelligent, informative",
      negative: "no photorealism, no glossy 3D rendering, no clutter, no multiple subjects",
    },
  },
  coverStyleRules: {
    "ukiyoe-cover": { label: "浮世絵カバー", baseKey: "ukiyoe" },
    "simple70s-cover": { label: "1970年代カバー", baseKey: "simple70s" },
    "retro80s-cover": { label: "1980年代カバー", baseKey: "retro80s" },
    "retro90s-cover": { label: "1990年代カバー", baseKey: "retro90s" },
    "retro2000s-cover": { label: "2000年代カバー", baseKey: "retro2000s" },
    "retro2010s-cover": { label: "2010年代カバー", baseKey: "retro2010s" },
    "retro2020s-cover": { label: "2020年代カバー", baseKey: "retro2020s" },
    "original-cover": { label: "オリジナルカバー", baseKey: "original" },
    "hokkaidoCamper-cover": { label: "北海道キャンピングカーカバー", baseKey: "hokkaidoCamper" },
  },
  styleOrder: [
    "ukiyoe",
    "simple70s",
    "retro80s",
    "retro90s",
    "retro2000s",
    "retro2010s",
    "retro2020s",
    "original",
    "hokkaidoCamper",
    "ukiyoe-cover",
    "simple70s-cover",
    "retro80s-cover",
    "retro90s-cover",
    "retro2000s-cover",
    "retro2010s-cover",
    "retro2020s-cover",
    "original-cover",
    "hokkaidoCamper-cover",
  ],
  textRules: {
    noText: {
      label: "文字なし",
      prompt: "no text, no typography, no letters, no words, no captions, purely visual storytelling",
    },
    unspecified: {
      label: "未指定",
      prompt: "",
    },
  },
  commonRules: [
    "convert the blog title into a strong visual concept rather than literal text rendering",
    "high visual clarity",
    "strong focal point",
    "iconic single subject",
    "visually cohesive",
    "clean composition",
  ],
  titleMappings: [
    {
      category: "danger",
      test: /(危ない|危険|注意|ヤバい|罠|失敗|やめたほうが|怖い)/i,
      mood: "cautionary, uneasy, subtle editorial tension",
      expression: "a guarded facial expression with visible caution",
    },
    {
      category: "compare",
      test: /(比較|違い|vs|対決|どっち|選び方|before|after|ビフォー|アフター)/i,
      mood: "clear contrast, analytical, structured clarity",
      expression: "a thoughtful person signaling contrast through posture or gaze",
    },
    {
      category: "roles",
      test: /(役割|人|チーム|体制|運用|整理|分担|担当|4人|３人|3人|5人)/i,
      mood: "thoughtful, structured, editorial clarity",
      expression: "a composed person embodying structure and responsibility",
    },
    {
      category: "season",
      test: /(桜|梅雨|雨|春|夏|秋|冬|紅葉|雪|季節|森|海|空|旅)/i,
      mood: "atmospheric, seasonal, emotionally calm, immersive",
      expression: "an emotionally resonant single motif shaped by weather and light",
    },
    {
      category: "explain",
      test: /(方法|使い方|とは|整理|まとめ|入門|初心者|完全ガイド|コツ|考え方)/i,
      mood: "informative, clear, confident, approachable",
      expression: "a clear symbolic figure or object with approachable presence",
    },
  ],
  abstractPeopleMap: [
    { test: /(利他|やさしさ|思いやり)/i, subject: "a single human figure with a calm and compassionate expression, symbolizing altruism" },
    { test: /(正義|信念|理念)/i, subject: "a single upright human figure with a steady and unwavering expression, symbolizing justice" },
    { test: /(不安|迷い|悩み)/i, subject: "a single human figure with a hesitant and uneasy expression, symbolizing anxiety" },
    { test: /(戦略|設計|戦術)/i, subject: "a single human figure with an intentional gaze and poised posture, symbolizing strategy" },
    { test: /(孤独|ひとり|孤立)/i, subject: "a single human figure in quiet isolation with a reflective expression, symbolizing solitude" },
    { test: /(危険|危ない|注意)/i, subject: "a single human figure with a guarded expression, symbolizing caution and risk" },
  ],
  compactSemanticRules: {
    subjects: [
      {
        words: ["Codex", "Claude Code", "AIブログ", "連載", "3連載"],
        subject: "a single symbolic human figure shaped by abstract intelligence motifs, with layered flowing forms integrated into one body to imply a crafted three-part editorial structure",
      },
      {
        words: ["江戸美人", "美人", "女人"],
        subject: "a single elegant Edo-period woman standing calmly in profile",
      },
      {
        words: ["女性", "女"],
        subject: "a single elegant woman presented as the dominant subject",
      },
      {
        words: ["男性", "男"],
        subject: "a single composed man presented as the dominant subject",
      },
      {
        words: ["旅人", "旅"],
        subject: "a single traveler shown as a calm symbolic figure",
      },
    ],
    emotions: [
      {
        words: ["喜ぶ", "うれしい", "嬉しい", "満足", "納得"],
        mood: "quiet satisfaction, internal recognition, refined joy",
        expression: "subtle restrained joy, calm and intelligent emotional tone",
      },
      {
        words: ["不安", "危険", "危ない", "警戒"],
        mood: "uneasy caution, restrained tension",
        expression: "a guarded expression with visible caution",
      },
      {
        words: ["静か", "静けさ", "穏やか"],
        mood: "calm, still, emotionally quiet",
        expression: "a restrained and peaceful expression",
      },
    ],
    transformations: [
      {
        words: ["3連載", "三連載", "連載", "シリーズ"],
        symbol: "three nested flowing layers fused into one coherent subject, symbolizing a designed multi-part series without separating into multiple objects",
        mood: "editorial structure, cohesive sequencing, designed continuity",
      },
      {
        words: ["設計", "構成", "整理", "プロンプト"],
        symbol: "refined internal patterning that suggests planning, orchestration, and intentional construction within one subject",
        mood: "designed precision, editorial intent, controlled generation",
      },
      {
        words: ["切り替わった", "切り替え", "更新", "改善", "進化", "向上", "整った"],
        symbol: "layered patterns transitioning from rough, slightly misaligned details into refined and harmonious details, symbolizing structural improvement",
        mood: "structural improvement, refined output, internal upgrade",
      },
      {
        words: ["比較", "違い", "before", "after", "ビフォー", "アフター"],
        symbol: "a visible contrast between rough and refined qualities within one subject",
        mood: "clear contrast, analytical improvement",
      },
    ],
    props: [
      {
        words: ["きれいな画像", "綺麗な画像", "美しい画像", "画像が作られている"],
        prop: "holding a small paper or silk sheet and gently observing its refined image quality",
      },
      {
        words: ["モデル", "AI", "ChatGPT", "Gemini"],
        prop: "a subtle sign of crafted output or refined generated work, without modern devices in view",
        mood: "quiet awareness of technical refinement and improved generation quality",
      },
      {
        words: ["Codex", "Claude Code", "プロンプト"],
        prop: "a subtle sign of crafted output or refined generated work, expressed as deliberate handmade refinement rather than tools or devices",
        mood: "quiet technical refinement, deliberate authorship, improved generative quality",
      },
      {
        words: ["紙", "原稿", "作品"],
        prop: "holding or facing a single crafted sheet or finished work",
      },
    ],
  },
  concreteMotifs: [
    { test: /(桜)/i, motif: "a single cherry blossom branch" },
    { test: /(雨|梅雨)/i, motif: "a single rain-soaked scene element" },
    { test: /(手相|手)/i, motif: "a single hand with visible palm lines" },
    { test: /(サウナ)/i, motif: "a single sauna stone stack with rising steam" },
    { test: /(森)/i, motif: "a single forest silhouette with strong atmosphere" },
    { test: /(ai|chatgpt|gemini)/i, motif: "a single symbolic human figure shaped by abstract intelligence motifs" },
  ],
  storageKey: "makeeyecatch.settings.v1",
  customStylesStorageKey: "makeeyecatch.custom_styles.v1",
  customStylesCookieKey: "makeeyecatch_custom_styles_meta",
  legacyCustomStylesCookieKey: "makeeyecatch_custom_styles",
};
